// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUfK3QEQNE5HUUJl5zELOAmNdcHod80I',
    appId: '1:94933890752:web:ffa641d64b7a92be605f25',
    messagingSenderId: '94933890752',
    projectId: 'stroke-gaurd-fyp25',
    authDomain: 'stroke-gaurd-fyp25.firebaseapp.com',
    storageBucket: 'stroke-gaurd-fyp25.firebasestorage.app',
    measurementId: 'G-4RX1TM6DNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiZz3bEhI-WjJM7UmOpENs_OAkTCr1yRM',
    appId: '1:94933890752:android:f40d20c96ce2ab03605f25',
    messagingSenderId: '94933890752',
    projectId: 'stroke-gaurd-fyp25',
    storageBucket: 'stroke-gaurd-fyp25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HkhnRBvnHz4lk9MLWURsi1PE2jdt85A',
    appId: '1:94933890752:ios:41b34705c26503f7605f25',
    messagingSenderId: '94933890752',
    projectId: 'stroke-gaurd-fyp25',
    storageBucket: 'stroke-gaurd-fyp25.firebasestorage.app',
    iosBundleId: 'com.example.strokeGaurd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5HkhnRBvnHz4lk9MLWURsi1PE2jdt85A',
    appId: '1:94933890752:ios:41b34705c26503f7605f25',
    messagingSenderId: '94933890752',
    projectId: 'stroke-gaurd-fyp25',
    storageBucket: 'stroke-gaurd-fyp25.firebasestorage.app',
    iosBundleId: 'com.example.strokeGaurd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrUfK3QEQNE5HUUJl5zELOAmNdcHod80I',
    appId: '1:94933890752:web:2ad46d6a51238e7a605f25',
    messagingSenderId: '94933890752',
    projectId: 'stroke-gaurd-fyp25',
    authDomain: 'stroke-gaurd-fyp25.firebaseapp.com',
    storageBucket: 'stroke-gaurd-fyp25.firebasestorage.app',
    measurementId: 'G-9WQ99VS9RB',
  );

}