// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC89wnrRG3hzdKJrv8JFh-HrnlWjB68i5Y',
    appId: '1:385659880170:web:e9f5eeb2a2051417208d93',
    messagingSenderId: '385659880170',
    projectId: 'flutter-login-app-8141c',
    authDomain: 'flutter-login-app-8141c.firebaseapp.com',
    storageBucket: 'flutter-login-app-8141c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEP8efMNuDYApEBIvT8dgww-U82UCvbag',
    appId: '1:385659880170:android:0ea6698239aa7802208d93',
    messagingSenderId: '385659880170',
    projectId: 'flutter-login-app-8141c',
    storageBucket: 'flutter-login-app-8141c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdfBlv_PVv5SMxajdc-cfE_xISbhpJgh4',
    appId: '1:385659880170:ios:8bdbc0f082f33786208d93',
    messagingSenderId: '385659880170',
    projectId: 'flutter-login-app-8141c',
    storageBucket: 'flutter-login-app-8141c.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC89wnrRG3hzdKJrv8JFh-HrnlWjB68i5Y',
    appId: '1:385659880170:web:ee8ca33b5e17f86f208d93',
    messagingSenderId: '385659880170',
    projectId: 'flutter-login-app-8141c',
    authDomain: 'flutter-login-app-8141c.firebaseapp.com',
    storageBucket: 'flutter-login-app-8141c.firebasestorage.app',
  );
}
